services:
  - type: web
    name: super-p2p-bootstrap
    env: python
    region: frankfurt
    plan: free
    branch: main

    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python server.py"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
