services:
  - type: web
    name: super-p2p
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
