services:
  - type: web
    name: super-p2p
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python super_p2p_v0_1_with_accounts.py"
    plan: free
    branch: main
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
